  0%|                                                                  | 0/17 [00:31<?, ?it/s]
torch.Size([32, 187, 32, 32]) torch.Size([32, 187, 282, 32])
Traceback (most recent call last):
  File "C:\Users\prana\Documents\Python_Stuff\Ariel-Data-Challenge-2024\main.py", line 65, in <module>
    train_valid_test(model = CNN(), train_loader = train_loader, valid_loader = valid_loader, loss_func = loss_func)
  File "C:\Users\prana\Documents\Python_Stuff\Ariel-Data-Challenge-2024\trainer.py", line 64, in __init__
    self.__train_init()
  File "C:\Users\prana\Documents\Python_Stuff\Ariel-Data-Challenge-2024\trainer.py", line 75, in __train_init
    running_loss = self.__train_core()
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prana\Documents\Python_Stuff\Ariel-Data-Challenge-2024\trainer.py", line 119, in __train_core
    loss = self.__run_batch(inps, label)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prana\Documents\Python_Stuff\Ariel-Data-Challenge-2024\trainer.py", line 133, in __run_batch
    preds = self.model(inps)
            ^^^^^^^^^^^^^^^^
  File "C:\Users\prana\Documents\Python_Stuff\Ariel-Data-Challenge-2024\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prana\Documents\Python_Stuff\Ariel-Data-Challenge-2024\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1603, in _call_impl
    result = forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prana\Documents\Python_Stuff\Ariel-Data-Challenge-2024\models\BasicCNN.py", line 86, in forward
    x = self.fc_block_1(x)
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\prana\Documents\Python_Stuff\Ariel-Data-Challenge-2024\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prana\Documents\Python_Stuff\Ariel-Data-Challenge-2024\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prana\Documents\Python_Stuff\Ariel-Data-Challenge-2024\.venv\Lib\site-packages\torch\nn\modules\container.py", line 219, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "C:\Users\prana\Documents\Python_Stuff\Ariel-Data-Challenge-2024\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prana\Documents\Python_Stuff\Ariel-Data-Challenge-2024\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prana\Documents\Python_Stuff\Ariel-Data-Challenge-2024\.venv\Lib\site-packages\torch\nn\modules\linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1507328 and 47104x2048)
